### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by matsimon** [fbagnol/class.unifi.php#1]
Dear author

Please consider adding a license under which you publish it. By not choosing a license your library is de factor to be considered closed source and not re-usable / extendable by anyone else.

Most UniFi API that have been written are published under a MIT or BSD style license.
A simple license chooser can be found on the (Github-sponsored) http://choosealicense.com/

**Comment by fbagnol** [comment]
it's done :)

**Comment by matsimon** [comment]
Thanks! Now your downstream can really use it, that is (not me), but:
https://github.com/malle-pietje/Unifi-API-browser
